/* AUTO-GENERATED by tools/wav_to_c.py — do not edit */
#pragma once
#include <stdint.h>
#include <stddef.h>

#define AUDIO_SAMPLE_RATE  8000U
#define AUDIO_SAMPLE_COUNT 29760U

extern const int16_t audio_pcm_data[];
extern const size_t  audio_pcm_sample_count;
