#!/usr/bin/env python3
"""Convert a 16kHz/16-bit/mono WAV file to a C array at 8kHz.

Usage:
    python3 wav_to_c.py <input.wav> <output_dir>

Reads mac_client/output/test.wav (16kHz, 16-bit, mono) and writes
src/audio_data.c and src/audio_data.h with the PCM data downsampled
to 8kHz by averaging pairs of consecutive samples.
"""

import struct
import sys
from pathlib import Path

PCM16_MAX = 32767
NORMALIZED_PEAK = int(PCM16_MAX * 0.9)


def read_wav_pcm(path: Path) -> tuple[int, int, int, bytes]:
    """Return (sample_rate, bit_depth, channels, raw_pcm_bytes)."""
    with open(path, "rb") as f:
        riff = f.read(12)
        if riff[:4] != b"RIFF" or riff[8:12] != b"WAVE":
            raise ValueError("Not a WAVE file")
        while True:
            chunk_header = f.read(8)
            if len(chunk_header) < 8:
                raise ValueError("fmt chunk not found")
            chunk_id = chunk_header[:4]
            chunk_size = struct.unpack_from("<I", chunk_header, 4)[0]
            if chunk_id == b"fmt ":
                fmt = f.read(chunk_size)
                audio_format = struct.unpack_from("<H", fmt, 0)[0]
                channels = struct.unpack_from("<H", fmt, 2)[0]
                sample_rate = struct.unpack_from("<I", fmt, 4)[0]
                bit_depth = struct.unpack_from("<H", fmt, 14)[0]
                if audio_format != 1:
                    raise ValueError(f"Only PCM WAV supported (format={audio_format})")
            elif chunk_id == b"data":
                pcm = f.read(chunk_size)
                return sample_rate, bit_depth, channels, pcm
            else:
                f.seek(chunk_size, 1)


def downsample_2x(samples: list[int]) -> list[int]:
    """Decimate by 2: average consecutive pairs."""
    out = []
    for i in range(0, len(samples) - 1, 2):
        avg = (samples[i] + samples[i + 1]) // 2
        out.append(avg)
    return out


def normalize_samples(samples: list[int], target_peak: int = NORMALIZED_PEAK) -> tuple[list[int], int]:
    """Scale PCM so the loudest sample reaches target_peak with clipping protection."""
    peak = max((abs(sample) for sample in samples), default=0)
    if peak == 0 or peak >= target_peak:
        return samples, 1

    gain = max(1, target_peak // peak)
    normalized = []
    for sample in samples:
        scaled = sample * gain
        if scaled > PCM16_MAX:
            scaled = PCM16_MAX
        elif scaled < -PCM16_MAX - 1:
            scaled = -PCM16_MAX - 1
        normalized.append(scaled)

    return normalized, gain


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    if len(sys.argv) >= 2:
        wav_path = Path(sys.argv[1])
    else:
        wav_path = repo_root.parent / "mac_client" / "output" / "test.wav"

    if len(sys.argv) >= 3:
        out_dir = Path(sys.argv[2])
    else:
        out_dir = repo_root / "src"

    print(f"Reading {wav_path}")
    sample_rate, bit_depth, channels, pcm_bytes = read_wav_pcm(wav_path)
    print(f"  Format: {sample_rate} Hz, {bit_depth}-bit, {channels} ch")

    if bit_depth != 16:
        raise ValueError(f"Expected 16-bit PCM, got {bit_depth}-bit")
    if channels != 1:
        raise ValueError(f"Expected mono, got {channels} channels")

    # Unpack int16_t samples
    n_samples = len(pcm_bytes) // 2
    samples = list(struct.unpack_from(f"<{n_samples}h", pcm_bytes))
    print(f"  Samples: {n_samples} ({n_samples / sample_rate:.2f}s)")

    # Downsample 16kHz -> 8kHz
    if sample_rate == 16000:
        samples = downsample_2x(samples)
        out_rate = 8000
    elif sample_rate == 8000:
        out_rate = 8000
    else:
        raise ValueError(f"Unsupported sample rate {sample_rate}; expected 16000 or 8000")

    print(f"  After downsample: {len(samples)} samples @ {out_rate} Hz "
          f"({len(samples) * 2 / 1024:.1f} KB)")

    samples, gain = normalize_samples(samples)
    peak = max((abs(sample) for sample in samples), default=0)
    print(f"  Normalized peak: {peak} / {PCM16_MAX} (gain x{gain})")

    # Write audio_data.h
    h_path = out_dir / "audio_data.h"
    with open(h_path, "w") as f:
        f.write("/* AUTO-GENERATED by tools/wav_to_c.py — do not edit */\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")
        f.write(f"#define AUDIO_SAMPLE_RATE  {out_rate}U\n")
        f.write(f"#define AUDIO_SAMPLE_COUNT {len(samples)}U\n\n")
        f.write("extern const int16_t audio_pcm_data[];\n")
        f.write("extern const size_t  audio_pcm_sample_count;\n")
    print(f"Wrote {h_path}")

    # Write audio_data.c
    c_path = out_dir / "audio_data.c"
    with open(c_path, "w") as f:
        f.write("/* AUTO-GENERATED by tools/wav_to_c.py — do not edit */\n")
        f.write('#include "audio_data.h"\n\n')
        f.write("const int16_t audio_pcm_data[] = {\n")
        cols = 12
        for i, s in enumerate(samples):
            if i % cols == 0:
                f.write("    ")
            f.write(f"{s:6d},")
            if (i + 1) % cols == 0:
                f.write("\n")
        if len(samples) % cols != 0:
            f.write("\n")
        f.write("};\n\n")
        f.write(f"const size_t audio_pcm_sample_count = {len(samples)}U;\n")
    print(f"Wrote {c_path}")


if __name__ == "__main__":
    main()
